### ISSUE TITLE
luck of documentation

### ISSUE THREAD

**Issue by budarin** [tunnckoCore/koa-better-serve#1]
Hi!

I tryed to config server for 3 hours but with result ((
I need send files in request "/assets/img1.jpg" my assets files are in the folder "../../dist"

How to configure server?
Help me please

**Comment by tunnckoCore** [comment]
Hi there.

First argument should be the folder where are the assets, second argument is "the url path".

If you have one `public` folder, in it you have `js`, `css` and `images` folders and you want they to be accessible through `yoursite.com/static` (e.g. `/static` path) you just need to do

```js
app.use(betterServe('./public', '/static'))
```

So in your case

```js
app.use(betterServe('../../dist', '/assets'))
```

I believe.

**Comment by budarin** [comment]
thanks!

**Comment by budarin** [comment]
I'm sorry, but when I try to access files from that path I've got the error:
**server error ForbiddenError: Forbidden**

I've tried also

``
app.use(staticServer("../../dist", "/assets", { root: path.resolve(__dirname, "../../dist") }));
``

but result is the same (
help me please

**Comment by tunnckoCore** [comment]
why set root option? And it's possible your user to don't have correct permissions for that dir.

It's simple. You just pass relative path as first argument - where "relative path" means relative to the file from where is called (e.g. server.js or something where the app is). You don't need to have both first argument and some option, and even more full absolute filepath.

I can't help much. Can you give some project folder structure? Where is the server file, what other config or build/transpile steps you do, what tools you use and etc.

**Comment by budarin** [comment]
```
/
dist/
   index.js <- assets
src/
  server/
      index.js  <- server script calls staticServer
```

**Comment by tunnckoCore** [comment]
Do you do some bundling/compiling/transpiling or etc stuff (babel, buble, webpack, rollup, postcss)? What OS you're using?

Is your images and "static files" are bundled in that `dist/index.js` file or they really exists physically on that directory?

**Comment by budarin** [comment]
I use webpack with such output configuration

```
output: {
        path: path.join(__dirname, 'dist'),
        publicPath: '/assets/',
        filename: '[name].js'
    },
```
also I use babel for transpiling my code
images, bundles and any resources are emited into /dist folder
on Windows

**Comment by tunnckoCore** [comment]
Don't know, sorry. Can't  reproduce the problem and can't help a lot with given responses. I tried.

In anyway everything is working - for me and not only for me, tests are passing, coverage is 100% and etc. It's just almost impossible to have some problem, because it is just few lines wrapper for `koa-send`.

If there's some problem, it may be in `koa-send` or your way of config of your machine, directories; or setup of your project, incorrect usage or something like that.

But it's not "lack of documentation", I can't see what I can say and document more.

**Comment by budarin** [comment]
thanks!

19.12.16 23:45, Charlike Mike Reagent пишет:
