### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by kjendrzyca** [tunnckoCore/koa-better-serve#4]
Hi

I was trying to use the package because it looks as simple as I would like it to. Unfortunately I can't make it work with any setup. Here are the details:

node version: `8.2.1`
koa version: `^2.3.0`

setup:
```
app.use(serve('../build'))

// also tried
app.use(serve('../build', ''))
app.use(serve('../build', '/'))
app.use(serve('../build', '/build'))
app.use(serve('./index.html', '/'))
app.use(serve('./index.html'))
```

error I got:

```
{ AssertionError [ERR_ASSERTION]: pathname required                                                                                                  [7/755]
    at /home/username/folder/node_modules/koa-send/index.js:39:5
    at Generator.next (<anonymous>)
    at onFulfilled (/home/username/folder/supplies/node_modules/co/index.js:65:19)
    at /home/username/folder/node_modules/co/index.js:54:5
    at Promise (<anonymous>)
    at co (/home/username/folder/node_modules/co/index.js:50:10)
    at send (/home/username/folder/node_modules/koa-send/index.js:36:10)
    at /home/username/folder/node_modules/koa-better-serve/index.js:69:16
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: '',
  expected: true,
  operator: '==' } { request: 
   { method: 'GET',
     url: '/',
     header: 
      { host: 'localhost:3001',
        connection: 'keep-alive',
        'cache-control': 'max-age=0',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Safari/537.36',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        dnt: '1',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4' } },
  response: { status: 404, message: 'Not Found', header: {} },
  app: { subdomainOffset: 2, proxy: false, env: 'production' },
  originalUrl: '/',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

**Comment by tunnckoCore** [comment]
Hello, sorry about that and thanks for the report.

Hm, that's a bit strange maybe. Probably you can try the pass `path.resolve('../build')`

```js
app.use(serve(path.resolve'../build', '/'))
```

Maybe last #2 is the reason.

**Comment by tunnckoCore** [comment]
Yea, there some bugs, only while looking over the code.

https://github.com/charlike/koa-better-serve/blob/master/index.js#L42 isn't okey too.

Sorry, i'll release a fix in coming days.

**Comment by tunnckoCore** [comment]
I refactored it, but still your case won't work because [the root path protection in `koa-send`](https://github.com/koajs/send/tree/v3.x#root-path). Which is kinda limiting, but in same time good thing.

Server should be in the top level, so you don't have to have `..` paths.

**Comment by tunnckoCore** [comment]
Sorry for that noise, just testing some automation and things. :)

**Comment by tunnckoCore** [comment]
Version `1.0.2` has been published to NPM. The full release note can be found at [koa-better-serve/releases/tag/v1.0.2](https://github.com/tunnckoCore/koa-better-serve/releases/tag/v1.0.2).

**Tip:** safely upgrade dependency koa-better-serve in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by tunnckoCore** [comment]
Don't install `1.0.2`. Automation tools suck :angry: :anger: Something failed, and i'll unpublish that specific version!

**Comment by charlike** [comment]
Version `1.1.0` has been published to NPM. The full release note can be found at [koa-better-serve/releases/tag/v1.1.0](https://github.com/tunnckoCore/koa-better-serve/releases/tag/v1.1.0).

**Tip:** safely upgrade dependency koa-better-serve in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by tunnckoCore** [comment]
Version `2.0.0` has been published to NPM. The full release note can be found at [koa-better-serve/releases/tag/v2.0.0](https://github.com/tunnckoCore/koa-better-serve/releases/tag/v2.0.0).

**Tip:** safely upgrade dependency koa-better-serve in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by tunnckoCore** [comment]
@kjendrzyca finally! :)

**Comment by kjendrzyca** [comment]
Thank you for the fix! Will try it soon.

**Comment by tunnckoCore** [comment]
It may not be a fix for you, but it is simplified and your case won't work even in only `koa-send`, so it's better to rethink the structure, probably :)

Good luck forward!
